title: Educalabs 
baseurl: /educalabs-laboratorio
email: contacto@educalabs.cl

highlighter: rouge
markdown: kramdown

# Tracker de analytics
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Optimizacion
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

exclude:
- README.md

gems: [jekyll-seo-tag, jekyll-paginate]